### ISSUE TITLE
GIF in readme? 

### ISSUE THREAD

**Issue by nym3r0s** [GokulSrinivas/vimrc#1]
Maybe add a gif in the README to make it easier.

**Comment by GokulSrinivas** [comment]
![vimrc](https://cloud.githubusercontent.com/assets/6184049/18015083/b70f0412-6be3-11e6-99ec-3e24c145beb2.gif)

**Comment by nym3r0s** [comment]
![output_qrby5y](https://cloud.githubusercontent.com/assets/6184049/18015626/1fceebdc-6be6-11e6-96c6-c5e369feac6c.gif)
